# Numpy



#### 1. Import the numpy package under the name `np` (★☆☆) 
(**hint**: import … as …)

In [2]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆) 
(**hint**: np.\_\_version\_\_, np.show\_config)

In [6]:
print(np.__version__)

1.22.3


#### 3. Create a null vector of size 10 (★☆☆) 
(**hint**: np.zeros)

In [9]:
x= np.zeros(10)
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4.  How to find the memory size of any array (★☆☆) 
(**hint**: size, itemsize)

In [8]:
x =np.zeros(10)
print(x.size) #size or lengh of the array will be return
print(x.itemsize) #returns the memory size

10
8


#### 5.  How to get the documentation of the numpy add function from the command line? (★☆☆) 
(**hint**: np.info)

In [10]:
import numpy as np
print(np.info(np.add))

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆) 
(**hint**: array\[4\])

In [11]:
x = np.zeros(10)
x[4]=1

print(x)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆) 
(**hint**: np.arange)

In [12]:
y = np.arange(10,49)
print(y)


[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]


#### 8.  Reverse a vector (first element becomes last) (★☆☆) 
(**hint**: array\[::-1\])

In [13]:
print(y[::-1])

[48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26 25
 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆) 
(**hint**: reshape)

In [17]:
z = np.arange(0,9).reshape(3,3)
print(z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆) 
(**hint**: np.nonzero)

In [18]:
a = [1,2,0,0,4,0]
b = np.nonzero(a)
print(b)

(array([0, 1, 4], dtype=int64),)


#### 11. Create a 3x3 identity matrix (★☆☆) 
(**hint**: np.eye)

In [20]:
e = np.eye(3)
print(e)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆) 
(**hint**: np.random.random)

In [23]:
a = np.random.random((3,3,3))
print(a)

[[[0.3976577  0.54239024 0.05852608]
  [0.52739712 0.45330984 0.79513883]
  [0.97330001 0.74569647 0.42522271]]

 [[0.76652066 0.38082324 0.25313557]
  [0.37358794 0.61633447 0.74041872]
  [0.51023635 0.61364545 0.16554048]]

 [[0.97208856 0.11257513 0.49738601]
  [0.48823009 0.94574244 0.66845918]
  [0.07952316 0.43589314 0.39160874]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆) 
(**hint**: min, max)

In [29]:
e = np.arange(1,101).reshape(10,10)
print(e)
#print(np.info(np.min))
print("Minimum value in the Array is:", np.min(e))
print("Maximum Value in the Array is",np.max(e))

[[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]]
Minimum value in the Array is: 1
Maximum Value in the Array is 100


#### 14. Create a random vector of size 30 and find the mean value (★☆☆) 
(**hint**: mean)

In [4]:
m = np.arange(30)
print(m)
print("Mean value",np.mean(m))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
Mean value 14.5


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆) 
(**hint**: array\[1:-1, 1:-1\])

In [6]:
q = np.ones(16).reshape(4,4)
q[1:-1,1:-1] = 0
print(q)


[[1. 1. 1. 1.]
 [1. 0. 0. 1.]
 [1. 0. 0. 1.]
 [1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆) 
(**hint**: np.pad)

In [8]:
x = np.arange(1,13).reshape(3,4)
y= np.pad(x,pad_width= 1,mode="constant",constant_values = 0)
print(y)

[[ 0  0  0  0  0  0]
 [ 0  1  2  3  4  0]
 [ 0  5  6  7  8  0]
 [ 0  9 10 11 12  0]
 [ 0  0  0  0  0  0]]


#### 17. What is the result of the following expression? (★☆☆) 
(**hint**: NaN = not a number, inf = infinity)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3 * 0.1
```

In [13]:
#0 * np.nan
print(0*np.nan)

#np.nan == np.nan
print(np.nan == np.nan)

#np.inf > np.nan
print(np.inf > np.nan)

#np.nan - np.nan
print(np.nan-np.nan)

#print(0.3 == 3 *0.1)
print(0.3 == 3* 0.1)



nan
False
False
nan
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆) 
(**hint**: np.diag)

In [15]:
x = np.diag([1,2,3,4],k= -1)
print(x)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆) 
(**hint**: array\[::2\])

In [8]:
x =np.zeros((8,8))



x[1::2,::2] = 1
x[::2,1::2] = 1
print(x)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? 
(**hint**: np.unravel_index)

In [11]:
print (np.unravel_index(100, (6,7,8)))
#print(np.info(np.unravel_index))

(1, 5, 4)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆) 
(**hint**: np.tile)

In [22]:
x =np.array([[1,0],[0,1]])
y=np.tile(x,(8,8))
print(y)


[[1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]]


#### 22. Normalize a 5x5 random matrix (★☆☆) 
(**hint**: (x - min) / (max - min))

In [26]:
x=np.random.random((5,5))
print(x)

print("Normalize a 5x5 random matrix")
xmax, xmin = x.max(), x.min()
x =(x-xmin) / (xmax-xmin)
print(x)

[[0.30623603 0.7331933  0.06901806 0.75520974 0.09025311]
 [0.98968152 0.12246374 0.673667   0.18124562 0.45592658]
 [0.51062314 0.21804666 0.13049328 0.71301331 0.7896402 ]
 [0.90604454 0.38355018 0.35446952 0.52572918 0.00311766]
 [0.23907703 0.43207593 0.35751041 0.1189617  0.52553801]]
Normalize a 5x5 random matrix
[[0.30724658 0.74001863 0.0667979  0.76233491 0.08832216]
 [1.         0.12097147 0.67968164 0.18055391 0.45897578]
 [0.51441726 0.21785614 0.12911037 0.7195638  0.79723428]
 [0.91522395 0.38561367 0.35613696 0.52972903 0.        ]
 [0.23917292 0.4348003  0.35921927 0.11742173 0.52953526]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆) 
(**hint**: np.dtype)

In [28]:
color = np.dtype([("r", np.ubyte, 1),
                  ("g", np.ubyte, 1),
                  ("b", np.ubyte, 1),
                  ("a", np.ubyte, 1)])

C:\Users\Rajaj\AppData\Local\Temp\ipykernel_6808\447806242.py:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  color = np.dtype([("r", np.byte, 1),


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆) 
(**hint**: np.dot | @)

In [32]:
x = np.dot(np.ones((5,3)),np.ones((3,2)))
print(x)

print("another method")
y = np.ones((5,3)) @ np.ones((3,2))
print(y)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]
another method
[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆) 
(**hint**: >, <=)

In [13]:
x = np.arange(11)
#y = x[(x>3) & (x <=8 )] * -1
#print(y)

x[(x>3) & (x <=8 )] *= -1
print(x)


[ 0  1  2  3 -4 -5 -6 -7 -8  9 10]


#### 26. What is the output of the following script? (★☆☆) 
(**hint**: np.sum)

```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))


#axisNone or int or tuple of ints, optional
#Axis or axes along which a sum is performed. 
#The default, axis=None, will sum all of the elements of the input array. 
#If axis is negative it counts from the last to the first axis

#The first line is equivalent to 0+1+2+3+4+(-1). 
#The third line is equivalent to 0+1+2+3+4 on axis=-1. 
#Use import numpy as np and then rewrite the third line as np.sum(range(5),-1). And read the documentation for np.sum()

```

In [22]:
#The first line is equivalent to 0+1+2+3+4+(-1). Output is 9
#The third line is equivalent to 0+1+2+3+4 on axis=-1. Output is 10

10
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [ ]:
#ValueError: Integers to negative integer powers are not allowed.

#### 28. What are the result of the following expressions?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [24]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

#output
#nan
#0
#[-2.14748365e+09]

nan
0
[-2.14748365e+09]


C:\Users\Rajaj\AppData\Local\Temp\ipykernel_5968\3912170336.py:1: RuntimeWarning: invalid value encountered in true_divide
  print(np.array(0) / np.array(0))
C:\Users\Rajaj\AppData\Local\Temp\ipykernel_5968\3912170336.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))


#### 29. How to round away from zero a float array ? (★☆☆) 
(**hint**: np.uniform, np.copysign, np.ceil, np.abs)

In [26]:
Z = np.random.uniform(-10,+10,10)
print (np.copysign(np.ceil(np.abs(Z)), Z))

#Need to understand more

[ 9.  9. -2. -1.  1. -9.  5.  5. -6.  4.]


#### 30. How to find common values between two arrays? (★☆☆) 
(**hint**: np.intersect1d)

In [31]:
Z1 = np.random.randint(0,10,10)
print(Z1)
Z2 = np.random.randint(0,10,10)
print(Z2)
print("Comman Values")
print(np.intersect1d(Z1,Z2))

[9 9 9 0 2 1 4 6 1 1]
[4 5 3 6 6 1 1 4 2 9]
Comman Values
[1 2 4 6 9]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆) 
(**hint**: np.seterr, np.errstate)

In [32]:
# Suicide mode on
defaults = np.seterr(all="ignore")
Z = np.ones(1) / 0

# Back to sanity
_ = np.seterr(**defaults)

An equivalent way, with a context manager:

with np.errstate(divide='ignore'):
    Z = np.ones(1) / 0
    
#Need to check it    

SyntaxError: invalid syntax (1205115598.py, line 8)

#### 32. Is the following expressions true? (★☆☆) 
(**hint**: imaginary number)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [ ]:
#/opt/conda/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
#  """Entry point for launching an IPython kernel.

#False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆) 
(**hint**: np.datetime64, np.timedelta64)

In [37]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
today     = np.datetime64('today', 'D')
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')

print(yesterday)
print(today)
print(tomorrow)

2022-10-29
2022-10-30
2022-10-31


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆) 
(**hint**: np.arange(dtype=datetime64\['D'\]))

In [38]:
Z = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(Z)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆) 
(**hint**: np.add(out=), np.negative(out=), np.multiply(out=), np.divide(out=))

In [39]:
A = np.ones(3)*1
B = np.ones(3)*2
C = np.ones(3)*3
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)

array([-1.5, -1.5, -1.5])

#### 36. Extract the integer part of a random array using 5 different methods (★★☆) 
(**hint**: %, np.floor, np.ceil, astype, np.trunc)

In [40]:
Z = np.random.uniform(0,10,10)

print (Z - Z%1)
print (np.floor(Z))
print (np.ceil(Z)-1)
print (Z.astype(int))
print (np.trunc(Z))

[5. 9. 3. 3. 3. 3. 2. 4. 2. 1.]
[5. 9. 3. 3. 3. 3. 2. 4. 2. 1.]
[5. 9. 3. 3. 3. 3. 2. 4. 2. 1.]
[5 9 3 3 3 3 2 4 2 1]
[5. 9. 3. 3. 3. 3. 2. 4. 2. 1.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆) 
(**hint**: np.arange)

In [44]:
Z = np.zeros((5,5))
Z = Z + np.arange(5)
print(Z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆) 
(**hint**: np.fromiter)

In [48]:
def generate():
    for x in range(10):
        yield x
Z = np.fromiter(generate(),dtype=int,count=-1)
print(Z)

[0 1 2 3 4 5 6 7 8 9]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆) 
(**hint**: np.linspace)

In [49]:
Z = np.linspace(0,1,11,endpoint=False)[1:]
print(Z)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 40. Create a random vector of size 10 and sort it (★★☆) 
(**hint**: sort)

In [52]:
Z = np.random.random(10)
Z.sort()
print(Z)


[0.17401721 0.34238269 0.374142   0.43653175 0.47634554 0.55209968
 0.7404705  0.83651998 0.8986725  0.96304277]


#### 41. How to sum a small array faster than np.sum? (★★☆) 
(**hint**: np.add.reduce)

In [54]:
Z = np.arange(10)
print(Z)
np.add.reduce(Z)

[0 1 2 3 4 5 6 7 8 9]


45

#### 42. Consider two random array A and B, check if they are equal (★★☆) 
(**hint**: np.allclose, np.array\_equal)

In [57]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)

# Assuming identical shape of the arrays and a tolerance for the comparison of values
print(A)
print(B)
equal = np.allclose(A,B)
print(equal)

# Checking both the shape and the element values, no tolerance (values have to be exactly equal)
equal = np.array_equal(A,B)
print(equal)

C = np.arange(1,11)
D = np.arange(1,11)
print(C)
print(D)

equal1 = np.allclose(C,D)
print(equal1)

equal1=np.array_equal(C,D)
print(equal1)

[1 1 1 1 1]
[1 1 1 0 1]
False
False
[ 1  2  3  4  5  6  7  8  9 10]
[ 1  2  3  4  5  6  7  8  9 10]
True
True


#### 43. Make an array immutable (read-only) (★★☆) 
(**hint**: flags.writeable)

In [59]:
Z = np.zeros(10)
Z.flags.writeable = False
Z[0] = 1

#Output = ValueError: assignment destination is read-only

ValueError: assignment destination is read-only

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆) 
(**hint**: np.sqrt, np.arctan2)

In [60]:
Z = np.random.random((10,2))
X,Y = Z[:,0], Z[:,1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
print(R)
print(T)

[0.70570775 0.6799793  0.63708935 0.73236959 1.20367604 0.91941016
 0.81585395 0.62811103 0.55456859 1.05494253]
[0.2817169  0.32319866 0.73018964 1.47005385 0.94272117 0.45934558
 1.14144411 0.68908443 0.27982078 0.48532697]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆) 
(**hint**: argmax)

In [64]:
Z = np.random.random(10)
Z[Z.argmax()] = 0
print(Z)

[0.80137394 0.56742805 0.01606472 0.05722497 0.80731434 0.
 0.26824292 0.52987935 0.75877171 0.94174755]


#### 46. Create a structured array with `x` and `y` coordinates covering the \[0,1\]x\[0,1\] area (★★☆) 
(**hint**: np.meshgrid)

In [65]:
Z = np.zeros((5,5), [('x',float),('y',float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,5),
                             np.linspace(0,1,5))
print(Z)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


####  47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) 
(**hint**: np.subtract.outer)

In [66]:
X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
print(np.linalg.det(C))

3638.163637117973


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆) 
(**hint**: np.iinfo, np.finfo, eps)

In [67]:
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 49. How to print all the values of an array? (★★☆) 
(**hint**: np.set\_printoptions)

In [68]:
Z = np.zeros((16,16))
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆) 
(**hint**: argmin)

In [72]:
Z = np.arange(100)
v = np.random.uniform(0,100)
index = (np.abs(Z-v)).argmin()
print(Z[index])
print(Z)
print(v)

31
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
31.400431301758115


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆) 
(**hint**: dtype)

In [73]:
Z = np.zeros(10, [ ('position', [ ('x', float, 1),
                                  ('y', float, 1)]),
                   ('color',    [ ('r', float, 1),
                                  ('g', float, 1),
                                  ('b', float, 1)])])
print(Z)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


C:\Users\Rajaj\AppData\Local\Temp\ipykernel_5968\274409719.py:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  Z = np.zeros(10, [ ('position', [ ('x', float, 1),


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆) 
(**hint**: np.atleast\_2d, T, np.sqrt)

In [74]:
Z = np.random.random((10,2))
X,Y = np.atleast_2d(Z[:,0], Z[:,1])
D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
print(D)

# Much faster with scipy
import scipy
# Thanks Gavin Heverly-Coulson (#issue 1)
import scipy.spatial

Z = np.random.random((10,2))
D = scipy.spatial.distance.cdist(Z,Z)
print(D)

[[0.         0.35881064 0.56632501 0.62178694 0.40506383 0.77231034
  0.33164383 0.41661821 0.82784563 0.57053966]
 [0.35881064 0.         0.90727454 0.39358212 0.06140871 0.74145127
  0.36237036 0.77532059 1.00068427 0.92658496]
 [0.56632501 0.90727454 0.         1.0330743  0.94084795 0.91955609
  0.67440032 0.25859985 0.61999063 0.13930227]
 [0.62178694 0.39358212 1.0330743  0.         0.33858888 0.44775032
  0.35959464 0.9943424  0.87079374 1.1009538 ]
 [0.40506383 0.06140871 0.94084795 0.33858888 0.         0.70765869
  0.35792509 0.82114245 0.99615068 0.96732996]
 [0.77231034 0.74145127 0.91955609 0.44775032 0.70765869 0.
  0.44682094 0.99704495 0.50827002 1.03224585]
 [0.33164383 0.36237036 0.67440032 0.35959464 0.35792509 0.44682094
  0.         0.64535058 0.63910486 0.74220538]
 [0.41661821 0.77532059 0.25859985 0.9943424  0.82114245 0.99704495
  0.64535058 0.         0.81454545 0.1800797 ]
 [0.82784563 1.00068427 0.61999063 0.87079374 0.99615068 0.50827002
  0.63910486 0.81454

ModuleNotFoundError: No module named 'scipy'

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place? 
(**hint**: astype(copy=False))

In [75]:
Z = np.arange(10, dtype=np.float32)
Z = Z.astype(np.int32, copy=False)
print(Z)

[0 1 2 3 4 5 6 7 8 9]


#### 54. How to read the following file? (★★☆) 
(**hint**: np.genfromtxt)

```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [76]:
from io import StringIO

# Fake file 
s = StringIO("""1, 2, 3, 4, 5\n
                6,  ,  , 7, 8\n
                 ,  , 9,10,11\n""")
Z = np.genfromtxt(s, delimiter=",", dtype=np.int)
print(Z)

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


C:\Users\Rajaj\AppData\Local\Temp\ipykernel_5968\1271915251.py:7: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  Z = np.genfromtxt(s, delimiter=",", dtype=np.int)


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆) 
(**hint**: np.ndenumerate, np.ndindex)

In [77]:
Z = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(Z):
    print(index, value)
for index in np.ndindex(Z.shape):
    print(index, Z[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 56. Generate a generic 2D Gaussian-like array (★★☆) 
(**hint**: np.meshgrid, np.exp)

In [78]:
X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
D = np.sqrt(X*X+Y*Y)
sigma, mu = 1.0, 0.0
G = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )
print(G)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

#### 57. How to randomly place p elements in a 2D array? (★★☆) 
(**hint**: np.put, np.random.choice)

In [79]:
n = 10
p = 3
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace=False),1)
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 1. 0. 0. 0.]]


#### 58. Subtract the mean of each row of a matrix (★★☆) 
(**hint**: mean(axis=,keepdims=))

In [80]:
# Author: Warren Weckesser

X = np.random.rand(5, 10)

# Recent versions of numpy
Y = X - X.mean(axis=1, keepdims=True)

# Older versions of numpy
Y = X - X.mean(axis=1).reshape(-1, 1)

print(Y)

[[ 0.33599406  0.02394537  0.13889855  0.11476376 -0.21865228 -0.08548461
  -0.46484028 -0.19209713  0.1423661   0.20510647]
 [ 0.43281645 -0.14295104 -0.19379811 -0.22365038 -0.15113151 -0.06285111
   0.10377622 -0.12300608 -0.20042833  0.56122388]
 [ 0.23286228  0.21311719 -0.48199606  0.46061183 -0.03696376 -0.48669249
  -0.49766862  0.12637572  0.21008063  0.26027327]
 [-0.44495846  0.01901994  0.4116554   0.21550485  0.3987014  -0.28869216
  -0.30646502 -0.53430479  0.26426711  0.26527172]
 [ 0.13711279  0.44156663 -0.36049423 -0.35228507 -0.18586816 -0.26398525
   0.05287    -0.30374481  0.33047746  0.50435065]]


#### 59. How to sort an array by the nth column? (★★☆) 
(**hint**: argsort)

In [81]:
Z = np.random.randint(0,10,(3,3))
print(Z)
print(Z[Z[:,1].argsort()])

[[2 4 6]
 [4 3 0]
 [5 2 4]]
[[5 2 4]
 [4 3 0]
 [2 4 6]]


#### 60. How to tell if a given 2D array has null columns? (★★☆) 
(**hint**: any, ~)

In [83]:
Z = np.random.randint(0,3,(3,10))
print((~Z.any(axis=0)).any())

False


#### 61. Find the nearest value from a given value in an array (★★☆) 
(**hint**: np.abs, argmin, flat)

In [84]:
Z = np.random.uniform(0,1,10)
z = 0.5
m = Z.flat[np.abs(Z - z).argmin()]
print(m)

0.4758139698088334


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆) 
(**hint**: np.nditer)

In [85]:
A = np.arange(3).reshape(3,1)
B = np.arange(3).reshape(1,3)
it = np.nditer([A,B,None])
for x,y,z in it: z[...] = x + y
print(it.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 63. Create an array class that has a name attribute (★★☆) 
(**hint**: class method)

In [86]:
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.info = getattr(obj, 'name', "no name")

Z = NamedArray(np.arange(10), "range_10")
print (Z.name)

range_10


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★) 
(**hint**: np.bincount | np.add.at)

In [87]:
Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
Z += np.bincount(I, minlength=len(Z))
print(Z)

# Another solution
# Author: Bartosz Telenczuk
np.add.at(Z, I, 1)
print(Z)

[3. 4. 2. 2. 1. 6. 4. 4. 2. 2.]
[ 5.  7.  3.  3.  1. 11.  7.  7.  3.  3.]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★) 
(**hint**: np.bincount)

In [88]:
X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,X)
print(F)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★) 
(**hint**: np.unique)

In [89]:
w,h = 16,16
I = np.random.randint(0,2,(h,w,3)).astype(np.ubyte)
#Note that we should compute 256*256 first. 
#Otherwise numpy will only promote F.dtype to 'uint16' and overfolw will occur
F = I[...,0]*(256*256) + I[...,1]*256 +I[...,2]
n = len(np.unique(F))
print(n)

8


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★) 
(**hint**: sum(axis=(-2,-1)))

In [90]:
A = np.random.randint(0,10,(3,4,3,4))
# solution by passing a tuple of axes (introduced in numpy 1.7.0)
sum = A.sum(axis=(-2,-1))
print(sum)
# solution by flattening the last two dimensions into one
# (useful for functions that don't accept tuples for axis argument)
sum = A.reshape(A.shape[:-2] + (-1,)).sum(axis=-1)
print(sum)

[[44 62 45 45]
 [58 60 59 72]
 [54 64 37 48]]
[[44 62 45 45]
 [58 60 59 72]
 [54 64 37 48]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★) 
(**hint**: np.bincount)

In [91]:
D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print(D_means)

# Pandas solution as a reference due to more intuitive code
import pandas as pd
print(pd.Series(D).groupby(S).mean())

[0.47378161 0.52166151 0.49354246 0.46426201 0.69800693 0.30808033
 0.6001626  0.53368256 0.51525847 0.36407859]
0    0.473782
1    0.521662
2    0.493542
3    0.464262
4    0.698007
5    0.308080
6    0.600163
7    0.533683
8    0.515258
9    0.364079
dtype: float64


#### 69. How to get the diagonal of a dot product? (★★★) 
(**hint**: np.diag)

In [92]:
A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))

# Slow version  
np.diag(np.dot(A, B))

# Fast version
np.sum(A * B.T, axis=1)

# Faster version
np.einsum("ij,ji->i", A, B)

array([0.89002887, 1.23667495, 1.25131977, 0.88649083, 1.02115189])

#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★) 
(**hint**: array\[::4\])

In [93]:
Z = np.array([1,2,3,4,5])
nz = 3
Z0 = np.zeros(len(Z) + (len(Z)-1)*(nz))
Z0[::nz+1] = Z
print(Z0)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★) 
(**hint**: array\[:, :, None\])

In [94]:
A = np.ones((5,5,3))
B = 2*np.ones((5,5))
print(A * B[:,:,None])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


#### 72. How to swap two rows of an array? (★★★) 
(**hint**: array\[\[\]\] = array\[\[\]\])

In [95]:
A = np.arange(25).reshape(5,5)
A[[0,1]] = A[[1,0]]
print(A)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★) 
(**hint**: repeat, np.roll, np.sort, view, np.unique)

In [96]:
faces = np.random.randint(0,100,(10,3))
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print(G)

[( 1, 22) ( 1, 37) ( 2,  9) ( 2, 62) ( 5, 32) ( 5, 88) ( 9, 62) (10, 48)
 (10, 51) (10, 84) (10, 90) (12, 82) (12, 97) (16, 82) (16, 88) (21, 55)
 (21, 96) (22, 34) (22, 37) (22, 47) (32, 88) (34, 47) (46, 80) (46, 85)
 (48, 84) (51, 90) (55, 96) (80, 85) (82, 88) (82, 97)]


#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★) 
(**hint**: np.repeat)

In [97]:
C = np.bincount([1,1,2,3,4,4,6])
A = np.repeat(np.arange(len(C)), C)
print(A)

[1 1 2 3 4 4 6]


#### 75. How to compute averages using a sliding window over an array? (★★★) 
(**hint**: np.cumsum)

In [98]:
def moving_average(a, n=3) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n
Z = np.arange(20)
print(moving_average(Z, n=3))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z\[0\],Z\[1\],Z\[2\]) and each subsequent row is  shifted by 1 (last row should be (Z\[-3\],Z\[-2\],Z\[-1\]) (★★★) 
(**hint**: from numpy.lib import stride_tricks)

In [99]:
from numpy.lib import stride_tricks

def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.itemsize, a.itemsize)
    return stride_tricks.as_strided(a, shape=shape, strides=strides)
Z = rolling(np.arange(10), 3)
print(Z)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★) 
(**hint**: np.logical_not, np.negative)

In [100]:
Z = np.random.randint(0,2,100)
np.logical_not(Z, out=Z)

Z = np.random.uniform(-1.0,1.0,100)
np.negative(Z, out=Z)

array([ 0.34460555, -0.59332782,  0.02389664,  0.79403468, -0.30745003,
       -0.63841191,  0.25632212, -0.32105393, -0.58107515,  0.71059608,
       -0.90581852, -0.09724686, -0.95329225, -0.73453463,  0.72045064,
        0.76579213,  0.30757587, -0.17015385,  0.8676672 , -0.146683  ,
        0.05452148, -0.12296216, -0.27495472,  0.10655737,  0.81643854,
        0.21089959, -0.71002423, -0.49135935, -0.53524361,  0.47468284,
        0.9108225 ,  0.89716952, -0.88875836,  0.76251059,  0.35825891,
       -0.51412821, -0.64900674,  0.99186427, -0.46170845, -0.67653621,
        0.67829011, -0.39746834, -0.16223451, -0.29361215,  0.86701125,
        0.35987869,  0.49980743,  0.6304675 ,  0.80903979, -0.24265362,
       -0.05523919, -0.46603207, -0.85322407, -0.69756086, -0.50862093,
        0.82376888,  0.20316738,  0.11169022,  0.8015674 , -0.5510897 ,
       -0.04813848, -0.74998437,  0.49127004,  0.49046002,  0.95005961,
        0.50963179, -0.72092528, -0.49974245, -0.54446014, -0.53

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i  (P0\[i\],P1\[i\])? (★★★)

In [101]:
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))
print(distance(P0, P1, p))

[10.43582674 13.47388027  6.57565311  3.12853342  7.02711764  8.52783157
 11.99787726  4.49655532  4.5828853   9.19889641]


#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P\[j\]) to each line i (P0\[i\],P1\[i\])? (★★★)

In [102]:
P0 = np.random.uniform(-10, 10, (10,2))
P1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10, 10, (10,2))
print(np.array([distance(P0,P1,p_i) for p_i in p]))

[[11.47681547  2.88666201  3.92597422  0.5343803   2.63950232  0.63870555
   5.29651443  2.38282709  0.66009413  0.5909062 ]
 [ 2.37833279  6.63640225  5.11638149  3.40688728 11.75642427  1.42903237
   1.46346694  7.40466086 11.52749419 14.84600671]
 [ 3.15774635  7.07932983  2.17672328  0.33524932  5.27457334  3.39275055
   0.27634348  4.47482752  4.36560952  8.1096754 ]
 [13.08431564  7.12462052 15.94315478 12.99950656 15.58700001 10.6981132
  13.54934905  8.35748783 13.30878556  0.42122587]
 [ 2.76524895 10.78669785  2.36055422  5.06671537  0.2661631   7.64386986
   3.27638597  6.57183726  0.55721935  7.49285647]
 [ 2.73937662  7.97811991  3.56836193  1.81915763 10.17463666  2.91043066
   2.60982477  8.28833326 10.00375493 14.88412404]
 [ 0.50133358  9.23723032  1.00903239  1.13711823  5.97467509  4.97256872
   2.97224653  7.64967941  5.53967441 11.84470904]
 [ 2.31048493 11.25539302  0.77572927  2.80488899  4.92963947  6.87068762
   5.04704824  9.70009736  4.73848682 13.41296838]
 

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★) 
(**hint**: minimum, maximum)

In [103]:
Z = np.random.randint(0,10,(10,10))
shape = (5,5)
fill  = 0
position = (1,1)

R = np.ones(shape, dtype=Z.dtype)*fill
P  = np.array(list(position)).astype(int)
Rs = np.array(list(R.shape)).astype(int)
Zs = np.array(list(Z.shape)).astype(int)

R_start = np.zeros((len(shape),)).astype(int)
R_stop  = np.array(list(shape)).astype(int)
Z_start = (P-Rs//2)
Z_stop  = (P+Rs//2)+Rs%2

R_start = (R_start - np.minimum(Z_start,0)).tolist()
Z_start = (np.maximum(Z_start,0)).tolist()
R_stop = np.maximum(R_start, (R_stop - np.maximum(Z_stop-Zs,0))).tolist()
Z_stop = (np.minimum(Z_stop,Zs)).tolist()

r = [slice(start,stop) for start,stop in zip(R_start,R_stop)]
z = [slice(start,stop) for start,stop in zip(Z_start,Z_stop)]
R[r] = Z[z]
print(Z)
print(R)

[[8 7 7 7 5 7 4 1 7 1]
 [3 9 9 2 5 6 8 6 2 7]
 [4 6 8 4 0 6 0 7 3 3]
 [9 1 1 5 9 2 8 9 8 5]
 [3 7 9 6 4 4 4 1 2 4]
 [8 7 9 4 4 5 9 2 7 2]
 [1 9 0 5 5 4 0 0 9 6]
 [5 4 7 3 8 8 6 6 8 8]
 [2 5 1 9 1 1 0 7 7 9]
 [2 0 2 0 2 2 4 8 2 4]]
[[0 0 0 0 0]
 [0 8 7 7 7]
 [0 3 9 9 2]
 [0 4 6 8 4]
 [0 9 1 1 5]]


C:\Users\Rajaj\AppData\Local\Temp\ipykernel_5968\1159162857.py:23: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  R[r] = Z[z]


#### 81. Consider an array Z = \[1,2,3,4,5,6,7,8,9,10,11,12,13,14\], how to generate an array R = \[\[1,2,3,4\], \[2,3,4,5\], \[3,4,5,6\], ..., \[11,12,13,14\]\]? (★★★) 
(**hint**: stride\_tricks.as\_strided)

In [104]:
Z = np.arange(1,15,dtype=np.uint32)
R = stride_tricks.as_strided(Z,(11,4),(4,4))
print(R)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 82. Compute a matrix rank (★★★) 
(**hint**: np.linalg.svd) (suggestion: np.linalg.svd)

In [105]:
Z = np.random.uniform(0,1,(10,10))
U, S, V = np.linalg.svd(Z) # Singular Value Decomposition
rank = np.sum(S > 1e-10)
print(rank)

10


#### 83. How to find the most frequent value in an array? 
(**hint**: np.bincount, argmax)

In [106]:
Z = np.random.randint(0,10,50)
print(np.bincount(Z).argmax())

3


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★) 
(**hint**: stride\_tricks.as\_strided)

In [107]:
Z = np.random.randint(0,5,(10,10))
n = 3
i = 1 + (Z.shape[0]-3)
j = 1 + (Z.shape[1]-3)
C = stride_tricks.as_strided(Z, shape=(i, j, n, n), strides=Z.strides + Z.strides)
print(C)

[[[[2 2 4]
   [1 3 0]
   [0 4 4]]

  [[2 4 0]
   [3 0 0]
   [4 4 4]]

  [[4 0 2]
   [0 0 3]
   [4 4 1]]

  [[0 2 3]
   [0 3 4]
   [4 1 2]]

  [[2 3 0]
   [3 4 2]
   [1 2 3]]

  [[3 0 0]
   [4 2 1]
   [2 3 4]]

  [[0 0 1]
   [2 1 2]
   [3 4 3]]

  [[0 1 2]
   [1 2 1]
   [4 3 4]]]


 [[[1 3 0]
   [0 4 4]
   [3 2 0]]

  [[3 0 0]
   [4 4 4]
   [2 0 3]]

  [[0 0 3]
   [4 4 1]
   [0 3 3]]

  [[0 3 4]
   [4 1 2]
   [3 3 3]]

  [[3 4 2]
   [1 2 3]
   [3 3 1]]

  [[4 2 1]
   [2 3 4]
   [3 1 2]]

  [[2 1 2]
   [3 4 3]
   [1 2 2]]

  [[1 2 1]
   [4 3 4]
   [2 2 2]]]


 [[[0 4 4]
   [3 2 0]
   [3 2 2]]

  [[4 4 4]
   [2 0 3]
   [2 2 3]]

  [[4 4 1]
   [0 3 3]
   [2 3 1]]

  [[4 1 2]
   [3 3 3]
   [3 1 4]]

  [[1 2 3]
   [3 3 1]
   [1 4 0]]

  [[2 3 4]
   [3 1 2]
   [4 0 2]]

  [[3 4 3]
   [1 2 2]
   [0 2 2]]

  [[4 3 4]
   [2 2 2]
   [2 2 1]]]


 [[[3 2 0]
   [3 2 2]
   [1 3 4]]

  [[2 0 3]
   [2 2 3]
   [3 4 3]]

  [[0 3 3]
   [2 3 1]
   [4 3 1]]

  [[3 3 3]
   [3 1 4]
   [3 1 2]]

  [[3 3 1]
   

#### 85. Create a 2D array subclass such that Z\[i,j\] == Z\[j,i\] (★★★) 
(**hint**: class method)

In [108]:
class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)

def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)

S = symetric(np.random.randint(0,10,(5,5)))
S[2,3] = 42
print(S)

[[ 5 11 14 16 10]
 [11  3  7  8  9]
 [14  7  4 42  6]
 [16  8 42  0  4]
 [10  9  6  4  5]]


#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★) 
(**hint**: np.tensordot)

In [109]:
p, n = 10, 20
M = np.ones((p,n,n))
V = np.ones((p,n,1))
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
print(S)

# It works, because:
# M is (p,n,n)
# V is (p,n,1)
# Thus, summing over the paired axes 0 and 0 (of M and V independently),
# and 2 and 1, to remain with a (n,1) vector.

[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★) 
(**hint**: np.add.reduceat)

In [110]:
Z = np.ones((16,16))
k = 4
S = np.add.reduceat(np.add.reduceat(Z, np.arange(0, Z.shape[0], k), axis=0),
                                       np.arange(0, Z.shape[1], k), axis=1)
print(S)

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


#### 88. How to implement the Game of Life using numpy arrays? (★★★)

In [111]:
def iterate(Z):
    # Count neighbours
    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
         Z[1:-1,0:-2]                + Z[1:-1,2:] +
         Z[2:  ,0:-2] + Z[2:  ,1:-1] + Z[2:  ,2:])

    # Apply rules
    birth = (N==3) & (Z[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)
    Z[...] = 0
    Z[1:-1,1:-1][birth | survive] = 1
    return Z

Z = np.random.randint(0,2,(50,50))
for i in range(100): Z = iterate(Z)
print(Z)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


#### 89. How to get the n largest values of an array (★★★) 
(**hint**: np.argsort | np.argpartition)

In [112]:
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5

# Slow
print (Z[np.argsort(Z)[-n:]])

# Fast
print (Z[np.argpartition(-Z,n)[:n]])

[9995 9996 9997 9998 9999]
[9998 9999 9995 9997 9996]


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★) 
(**hint**: np.indices)

In [113]:
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

print (cartesian(([1, 2, 3], [4, 5], [6, 7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


#### 91. How to create a record array from a regular array? (★★★) 
(**hint**: np.core.records.fromarrays)

In [114]:
Z = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
R = np.core.records.fromarrays(Z.T, 
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
print(R)

[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]


#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★) 
(**hint**: np.power, \*, np.einsum)

In [115]:
x = np.random.rand(5e7)

%timeit np.power(x,3)
%timeit x*x*x
%timeit np.einsum('i,i,i->i',x,x,x)

TypeError: 'float' object cannot be interpreted as an integer

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★) 
(**hint**: np.where)

In [116]:
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))

C = (A[..., np.newaxis, np.newaxis] == B)
rows = np.where(C.any((3,1)).all(1))[0]
print(rows)

[4]


#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. \[2,2,3\]) (★★★)

In [117]:
Z = np.random.randint(0,5,(10,3))
print(Z)
# solution for arrays of all dtypes (including string arrays and record arrays)
E = np.all(Z[:,1:] == Z[:,:-1], axis=1)
U = Z[~E]
print(U)
# soluiton for numerical arrays only, will work for any number of columns in Z
U = Z[Z.max(axis=1) != Z.min(axis=1),:]
print(U)

[[3 2 1]
 [2 3 3]
 [4 4 1]
 [0 3 4]
 [3 1 1]
 [0 1 2]
 [3 2 0]
 [2 1 3]
 [3 1 0]
 [3 2 2]]
[[3 2 1]
 [2 3 3]
 [4 4 1]
 [0 3 4]
 [3 1 1]
 [0 1 2]
 [3 2 0]
 [2 1 3]
 [3 1 0]
 [3 2 2]]
[[3 2 1]
 [2 3 3]
 [4 4 1]
 [0 3 4]
 [3 1 1]
 [0 1 2]
 [3 2 0]
 [2 1 3]
 [3 1 0]
 [3 2 2]]


#### 95. Convert a vector of ints into a matrix binary representation (★★★) 
(**hint**: np.unpackbits)

In [118]:
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128])
B = ((I.reshape(-1,1) & (2**np.arange(8))) != 0).astype(int)
print(B[:,::-1])

# Author: Daniel T. McDonald

I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128], dtype=np.uint8)
print(np.unpackbits(I[:, np.newaxis], axis=1))

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]
[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


#### 96. Given a two dimensional array, how to extract unique rows? (★★★) 
(**hint**: np.ascontiguousarray)

In [119]:
Z = np.random.randint(0,2,(6,3))
T = np.ascontiguousarray(Z).view(np.dtype((np.void, Z.dtype.itemsize * Z.shape[1])))
_, idx = np.unique(T, return_index=True)
uZ = Z[idx]
print(uZ)

# Author: Andreas Kouzelis
# NumPy >= 1.13
uZ = np.unique(Z, axis=0)
print(uZ)

[[0 0 0]
 [0 0 1]
 [1 1 0]]
[[0 0 0]
 [0 0 1]
 [1 1 0]]


#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★) 
(**hint**: np.einsum)

In [120]:
A = np.random.uniform(0,1,10)
B = np.random.uniform(0,1,10)

np.einsum('i->', A)       # np.sum(A)
np.einsum('i,i->i', A, B) # A * B
np.einsum('i,i', A, B)    # np.inner(A, B)
np.einsum('i,j->ij', A, B)    # np.outer(A, B)

array([[0.04784231, 0.06480641, 0.32864079, 0.04357704, 0.20656466,
        0.14792005, 0.34261776, 0.18844129, 0.18440162, 0.02357674],
       [0.03156396, 0.04275603, 0.21682075, 0.02874995, 0.13628102,
        0.09759025, 0.22604205, 0.12432413, 0.12165896, 0.01555475],
       [0.07666012, 0.10384255, 0.52659758, 0.06982567, 0.33098889,
        0.2370197 , 0.54899358, 0.3019489 , 0.29547594, 0.03777818],
       [0.08768982, 0.1187832 , 0.60236332, 0.07987204, 0.37861086,
        0.27112159, 0.62798161, 0.34539267, 0.33798839, 0.04321363],
       [0.01939152, 0.02626744, 0.13320521, 0.01766272, 0.08372512,
        0.05995519, 0.13887038, 0.07637932, 0.07474196, 0.00955616],
       [0.05573411, 0.07549652, 0.38285157, 0.05076527, 0.24063843,
        0.17232013, 0.3991341 , 0.21952553, 0.2148195 , 0.02746583],
       [0.08875364, 0.12022424, 0.60967098, 0.08084102, 0.38320404,
        0.27441074, 0.63560006, 0.34958285, 0.34208875, 0.04373788],
       [0.08660473, 0.11731336, 0.5949096

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)? 
(**hint**: np.cumsum, np.interp)

In [121]:
phi = np.arange(0, 10*np.pi, 0.1)
a = 1
x = a*phi*np.cos(phi)
y = a*phi*np.sin(phi)

dr = (np.diff(x)**2 + np.diff(y)**2)**.5 # segment lengths
r = np.zeros_like(x)
r[1:] = np.cumsum(dr)                # integrate path
r_int = np.linspace(0, r.max(), 200) # regular spaced path
x_int = np.interp(r_int, r, x)       # integrate path
y_int = np.interp(r_int, r, y)

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★) 
(**hint**: np.logical\_and.reduce, np.mod)

In [122]:
X = np.asarray([[1.0, 0.0, 3.0, 8.0],
                [2.0, 0.0, 1.0, 1.0],
                [1.5, 2.5, 1.0, 0.0]])
n = 4
M = np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)
M &= (X.sum(axis=-1) == n)
print(X[M])

[[2. 0. 1. 1.]]


#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★) 
(**hint**: np.percentile)

In [123]:
X = np.random.randn(100) # random 1D array
N = 1000 # number of bootstrap samples
idx = np.random.randint(0, X.size, (N, X.size))
means = X[idx].mean(axis=1)
confint = np.percentile(means, [2.5, 97.5])
print(confint)

[-0.22185851  0.15743215]
